eventFinderApp/eventFinderProject/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from django.views.generic.base import TemplateView
from rest_framework import routers
from eventFinderApp import viewsets
from rest_framework.authtoken import views
from django.conf import settings
from django.conf.urls.static import static
from users import viewsets as UserViewsets

# from django.conf import settings
# from django.conf.urls.static import static

router = routers.DefaultRouter()
router.register(r'events', viewsets.EventViewSet)
router.register(r'users', UserViewsets.CustomUserViewSet)


urlpatterns = [
    path("", include("eventFinderApp.urls")),
    # path('', TemplateView.as_view(template_name='index.html'), name='index'),
    url(r"^admin/", admin.site.urls),
    path("users/", include("django.contrib.auth.urls")),
    path("users/", include("users.urls")),
    path("profile/edit/", include("users.urls")),
    path('api/', include(router.urls)),
    path(r'api-auth-token/', views.obtain_auth_token),
    
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eventFinderApp/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from . import views
from django.conf.urls import url

app_name = 'eventFinderApp'


urlpatterns = [

    # event-finder/

    path('', views.IndexView.as_view(), name='index'),

    # event-finder/1

    path('eventFinder/<int:pk>/', views.EventView.as_view(), name='event'),

    # event-finder/my-account

    path('my-account/', views.AccountView.as_view(), name='account'),

    # event-finder/add-event

    path('eventFinder/addevent/', views.addevent, name='addevent'),
    path('eventFinder/<id>/editevent/', views.editevent, name='editevent'),

    # path(r'^eventFinder/event/(?P<id>\d+)/$', views.editevent, name='editevent'),

    # path('eventFinder/(?P<id>\d+)/', views.editevent, name='edit'),

    # url(r'^eventFinderApp/addevent/$', views.addevent, name='addevent'),



    # event-finder/user

    # path("event/edit/", views.edit_event, name="edit_event"),
    # path('thanks/', views.thankyouView.as_view(), name='thanks'),

    # path('eventFinder/thanks/', TemplateView.as_view(template_name="thanks")),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eventFinderProject/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from django.views.generic.base import TemplateView
from rest_framework import routers
from eventFinderApp import viewsets
from rest_framework.authtoken import views
from django.conf import settings
from django.conf.urls.static import static
from users import viewsets as UserViewsets

# from django.conf import settings
# from django.conf.urls.static import static

router = routers.DefaultRouter()
router.register(r'events', viewsets.EventViewSet)
router.register(r'users', UserViewsets.CustomUserViewSet)


urlpatterns = [
    path("", include("eventFinderApp.urls")),
    # path('', TemplateView.as_view(template_name='index.html'), name='index'),
    url(r"^admin/", admin.site.urls),
    path("users/", include("django.contrib.auth.urls")),
    path("users/", include("users.urls")),
    path("profile/edit/", include("users.urls")),
    path('api/', include(router.urls)),
    path(r'api-auth-token/', views.obtain_auth_token),
    # url(r'^$/', include('eventFinderApp.urls')), #added this.
    
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, include
from django.conf.urls import include, url   
from . import views
from django.conf.urls.static import static
from django.views.generic import TemplateView

# from django.contrib.auth import views as auth_views




urlpatterns = [

    path("register/", views.Register.as_view(), name="register"),
    path("profile/edit/", views.edit_profile, name="edit_profile"),
    # url(r'^profile/edit/$', views.edit_profile, name = "edit_profile"),
    url(r'^profile/$', views.view_profile, name="view_profile"),
    # url(r'^change_password/$', views.change_password, name="change_password"),  
    # path('upload/', views.upload, name='upload'),
    path('pics/upload/', views.upload_pic, name="pic"),
    path("profile/password", views.change_password, name="edit password"),

]

eventFinderApp/models.py
from django.db import models
from django.forms import ModelForm
from django.urls import reverse
from django.contrib.auth.models import Permission
from django.contrib.auth import get_user_model

User = get_user_model()


class Event(models.Model):
    title = models.CharField(max_length=200)
    location = models.CharField(max_length=200)
    venue = models.CharField(max_length=200)
    start_time = models.DateTimeField('start time and date')
    end_time = models.DateTimeField('end time and date')
    categories = models.ManyToManyField('Category', related_name='events')
    host = models.ForeignKey(User, on_delete=models.CASCADE, related_name='events', blank=True)
    # image = models.ImageField(upload_to='profile_image', blank=True)

    # email = models.ForeignKey(email, on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

eventFinderApp/forms.py
from django import forms
from django.forms import ModelForm
from .models import Event, Category
from django.contrib.admin import widgets
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _


class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = [
           'title',
           'venue',
           'location',
           'start_time',
           'end_time',
           'categories',
           'host',
        ]

    def __init__(self, *args, **kwargs):
        super(EventForm, self).__init__(*args, **kwargs)
        # self.fields['start_time'].widget = widgets.AdminDateWidget()
        # self.fields['end_time'].widget = widgets.AdminTimeWidget()
        self.fields['start_time'].widget = widgets.AdminSplitDateTime()
        self.fields['end_time'].widget = widgets.AdminSplitDateTime()

    # def clean_renewal_date(self):
    #     data = self.cleaned_data['renewal_date']
        
    #     # Check if a date is not in the past. 
    #     if data < datetime.date.today():
    #         raise ValidationError(_('Invalid date - event in past'))

    #     # Check if a date is in the allowed range (+4 weeks from today).
    #     if data > datetime.date.today() + datetime.timedelta(weeks=52):
    #         raise ValidationError(_('Invalid date - renewal more than 52 weeks ahead'))

    #     # Remember to always return the cleaned data.
    #     return data


class EditEventForm(ModelForm):
    class Meta:
        model = Event
        fields = [
                 'title',
                 'venue',            
        ]


# class DateInput(forms.DateInput):
#  input_type = 'date'

eventFinderApp/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.shortcuts import render, redirect, get_object_or_404
from .models import Event
from .forms import EventForm, EditEventForm
from django.contrib import messages


class IndexView(generic.ListView):
    template_name = "eventFinderApp/index.html"
    context_object_name = "events_list"
    

    def get_queryset(self):
        """Return the events."""
        return Event.objects.all()



    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['filter'] = EventFilter(self.request.GET, queryset=self.get_queryset())
    #     return context


class AccountView(generic.ListView):
    template_name = "eventFinderApp/account.html"
    context_object_name = "events_list"

    def get_queryset(self):
        """Return the events."""
        return Event.objects.filter(host=self.request.user)


class EventView(generic.DetailView):
    model = Event
    template_name = "eventFinderApp/event.html"


def account(request):
    return render(request, "eventFinderApp/account.html")





def addevent(request):
    if request.method =="POST":
        form = EventForm(request.POST)
        if form.is_valid():
            event_item = form.save(commit=False)
            event_item.save()
    else:
        form = EventForm()
    return render(request, 'EventFinderApp/account.html', {'form': form})


def editevent(request, id=None):
    item = get_object_or_404(Event, id=id)
    form = EditEventForm(request.POST or None, instance=item)
    if form.is_valid():
        event_item = form.save(commit=False)
        event_item.save()
    else:
        form = EditEventForm
    return render(request, 'eventFinderApp/editevent.html', {'form': form})


# class EditEventView(generic.UpdateView):
    
#     model = Event

#     form_class = EventForm

#     success_url = reverse_lazy('eventFinderApp:account')

#     template_name = 'eventFinderApp/edit_event.html'

# def edit_event(request, pk):
#     # post = get_object_or_404(Event, pk=pk)
#     if request.method == "POST":
#         form = EventForm(request.POST, instance=Event)
#         if form.is_valid():
#             event = form.save(commit=False)
#             event.author = request.user
#             # event.published_date = timezone.now()
#             event.save()
#             return redirect('EventView', pk=event.pk)
#     else:
#         form = EventForm(instance=event)
#     return render(request, 'eventFinder/edit_event.html', {'form': form})


#here is what i had before djangogirls tutorial:
# # the fucntional view for add event
# def addevent(request):
#     # if this is a POST request we need to process the form data
#     if request.method == 'POST':
#         # create a form instance and populate it with data from the request:
#         form = EventForm(request.POST)
        
#         # check whether it's valid:
#         if form.is_valid():
           
#             # process the data in form.cleaned_data as required
#             # ...
#             # redirect to a new URL:
#             return HttpResponseRedirect('/thanks/')

#     # if a GET (or any other method) we'll create a blank form
#     else:
#         form = EventForm()

#     return render(request, 'eventFinderApp/index.html', {'form': form})

# context = {
#         'form': form,
#         'book_instance': book_instance,
#     }

#     return render(request, 'catalog/book_renew_librarian.html', context)





# mine original
# from django.http import HttpResponse, HttpResponseRedirect
# from django.urls import reverse, reverse_lazy
# from django.views import generic
# from django.shortcuts import render
# from .models import Event
# from .forms import EventForm
# from django.contrib import messages


# class IndexView(generic.ListView):
#     template_name = "eventFinderApp/index.html"
#     context_object_name = "events_list"

#     def get_queryset(self):
#         """Return the events."""
#         return Event.objects.all().order_by('start_time')


# class AccountView(generic.ListView):
#     template_name = "eventFinderApp/account.html"
#     context_object_name = "events_list"

#     def get_queryset(self):
#         """Return the events."""
#         return Event.objects.filter(host=self.request.user).order_by('start_time')


# class EventView(generic.DetailView):
#     model = Event
#     template_name = "eventFinderApp/event.html"


# def account(request):
#     return render(request, "eventFinderApp/account.html")


# # the fucntional view for add event
# def addevent(request):
    
#     form = EventForm(request.POST)
#     # success = False
#     # if this is a POST request we need to process the form data
#     if request.method == "POST":
#         # create a form instance and populate it with data from the request:
        
#         # check whether it's valid:
#         if form.is_valid():
#             # save the data from the form
#             # new_event = form.save(commit=False)
#             # new_event.host = request.user
#             form.save()
#             messages.success(request, 'details updated.')
#             # success = True
#             # redirect to the event list
#             return render(request, "eventFinderApp/thanks")
#     # if a GET (or any other method) we'll create a blank form
#     else:
#         form = EventForm()
#     # return the invalid or new form to the template
#     return render(request, 'eventFinderApp/thanks.html', {'form': EventForm})


# # the Class based view for add event
# class AddEventView(generic.View):
#     # in the class basded view we handle the GET request with a get() function
#     def get(self, request):
#         # create our form instance
#         form = EventForm()
#         # assign it to the context
#         context = {"form": eventform}
#         # return our template with our context
#         template = "eventFinderApp/addevent.html"
#         return render(request, template, context)

#     # in the class based view we handle the POST request with a post() function
#     def post(self, request):
#         # we create our form instance with the data from the request
#         form = EventForm(request.POST)
#         # check if the form is valid
#         if form.is_valid():
#             # save the data of the form
#             form.save()
#             messages.success(request, 'details updated.')
#             # redirect to the list of events
#             return render(request, "eventFinderApp/thanks")
#             # return HttpResponseRedirect(reverse("eventFinderApp/thanks"))
#         # if the form isn't valid return the form (with automatic errors)
#         # create the context for our template
#         context = {"form": EventForm}
#         # build the response with our template
#         template = "eventFinderApp/addevent.html"
#         return render(request, template, context)

eventFinderApp/templates/eventFinderApp/account.html
{% extends "base.html" %}
{% block content %}



<p> Welcome  {{ user.username }} </p>


<div class="container">

<h3>Profile</h3>
<br>

<p>Username: {{ user.username }}</p>

<p>First Name: {{ user.first_name }}</p>

<p>Last Name: {{ user.last_name }}</p>

<h4>Email: {{ user.email }}</h4>
<br>


<form>
<a href = '\users\profile\edit'>Click here to edit your profile</a>


</form>

<h3>Your events:</h3>

    {% if events_list %}

        {% for event in events_list %}

            {% include "./detailsBox.html" with event=event %}

        {% endfor %}

    {% else %}

        <p>You're not hosting any events.</p>

    {% endif %}

    <br>

{% endblock %} 

eventFinderApp/templates/eventFinderApp/addevent.html
{% extends "base.html" %}

{% block content %}
{% load crispy_forms_tags %}



<div class = "event-container">

<h2>Add Event</h2>

    {% comment %} <form method="POST" class="event-form">{% csrf_token %} {% endcomment %}
    <form class='' action="" method="post"> {% csrf_token %} 
      {{ form|crispy }}
 
        <input type="submit" value="save"
    </form>


        {% comment %} <form action="" method="post">
                {% csrf_token %}
                {{ form|crispy }}
           
                <input type="submit" value="Create" id="submit">
        </form> {% endcomment %}


            {% comment %} {% if messages %}
                <ul class="messages">
                        {% for message in messages %}
                        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                        {% endfor %}
                </ul>
            {% endif %} {% endcomment %}
</div>
{% endblock %}


{% comment %} //if submit shows a message - else show the form
   get rid of the thanks  {% endcomment %}

eventFinderApp/templates/eventFinderApp/base.html
{% load static %}

<!doctype html>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>EventFinda</title>
        <meta name="description" content="">
        <meta name="author" content="Angela Moroney">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link href="https://fonts.googleapis.com/css?family=Manjari&display=swap" rel="stylesheet">
       
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    </head>

    <body>
        <header>
            <div>
                <h1>EventFinda</h1>
                <h2>Find free events near you!</h2>
            </div>
            {% include './nav.html' %}
        </header>
        {% comment %} <a href="{% url 'addevent' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a> {% endcomment %}

        {% block content %}{% endblock %}
    </body>
</html>

        {% comment %} <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"> {% endcomment %}

eventFinderApp/templates/eventFinderApp/detailsBox.html
{% comment %} {% extends "base.html" %} {% endcomment %}
{% block content %}

<div class="details-box">
    <a href="{% url 'eventFinderApp:event' event.id %}">
        <p>title: {{ event.title }}</p>
       
        <p>venue: {{ event.venue }}<p>
        <p>categories: 
            {% for cat in event.categories.all %}
                {{ cat }}
                {% if not forloop.first and not forloop.last %}
                    ,
                {% endif %}
            {% endfor %}
        </p>
        <br>
        <h4>start: {{ event.start_time }}</h4>
        <h4>end: {{ event.end_time }}</h4>
    </a>
</div>

{% comment %} 
<button type="submit">
<h5> edit event? </h5>
</button> {% endcomment %}
<br>
<br>

{% comment %} 
<div class="container">
    <form method="post" >
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
    <br>
</div> {% endcomment %}


</div>


{% endblock %}

eventFinderApp/templates/eventFinderApp/editevent.html
{% extends 'eventFinderApp/base.html' %}


{% load static %}

<!doctype html>

<br>
<br>
<strong> edit event? </strong>
<br>
<br>

<title>Profile</title>

{% block content %}
   

<div class="container">
    <form method="POST" class="EditEventForm">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit"class="save btn btn-default">Save</button>
    </form>
    <br>
</div> 

{% endblock %}
</div>

eventFinderApp/templates/eventFinderApp/event.html
{% extends "base.html" %}

{% block content %}

<h2>{{ event.title }}</h2>
<br>

<p>{{ event.location }}</p>
<p>{{ event.venue }} </p>
<h4>Starts at: {{ event.start_time }}</h4>
<h4>Ends at: {{ event.end_time }}</h4>
<br>
<h6> Why not go along! </h6>
 <a href="{{EditEventForm}}"><button id="edit-event"> Edit event</button></a>

{% endblock %} 



{% comment %} {% extends 'base.html' %}

{% block content %}
    <div class="event">
        {% if event.published_date %}
            <div class="date">
                {{ post.published_date }}
            </div>
        {% endif %}
        <a class="btn btn-default" href="{% url 'edit_event' pk=post.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
        <h2>{{ event.title }}</h2>
        <p>{{ event.text|linebreaksbr }}</p>
    </div>
{% endblock %} {% endcomment %}

eventFinderApp/templates/eventFinderApp/index.html
{% extends "./base.html" %}

{% load staticfiles %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="{% static 'eventFinderApp/style.css' %}" />



{% block content %}

    <a href="{% url 'eventFinderApp:addevent' %}"><button id="new-event">+ Create new event</button></a>
    <h3>See what's on!</h3>
    {% if events_list %}
        {% for event in events_list %}
            {% include "./detailsBox.html" with event=event %}
        {% endfor %}
    {% else %}
        <p>No events are available.</p>
    {% endif %}

{% endblock %}

eventFinderApp/templates/eventFinderApp/nav.html
{% load staticfiles %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons"> 
<link rel="stylesheet" type="text/css" href="{% static 'eventFinderApp/style.css' %}" />


<nav class="navbar navbar-expand-lg navbar-light bg-light">

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">

          <span class="navbar-toggler-icon"></span>

        </button>

      

        <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
        
          <ul class="navbar-nav mr-auto mt-2 mt-lg-0">

            <li class="nav-item active">

                    <a class="nav-link" href="{% url 'eventFinderApp:index' %}">Homme</a>            </li>

            <li class="nav-item">

                    <a class="nav-link" href="{% url 'eventFinderApp:account' %}">My Account</a>            </li>

            <li class="nav-item">

                    {% if user.is_authenticated %}

                    <a class="nav-link">Hi {{ user.username }}</a>

                    <a class="nav-link" href="{% url 'logout' %}">logout</a></li>

                {% else %}

                    <a class="nav-link" href="{% url 'login' %}">loginn</a></p>

                    <a class="nav-link" href="{% url 'register' %}">register</a></p>

                {% endif %}            </li>

          </ul>

          <form class="form-inline my-2 my-lg-0">

            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">

            <button type="submit" class="w3-bar-item w3-button w3-green"><i class="material-icons">search</i></button>

           
            {% comment %} <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button> {% endcomment %}

          </form>

        </div>

      </nav>



{% comment %} in case it goes wrong - here's what i had before: {% endcomment %}

{% comment %} 

      {% load staticfiles %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="{% static 'eventFinderApp/style.css' %}" />


<nav class="navbar navbar-expand-lg navbar-light bg-light">

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">

          <span class="navbar-toggler-icon"></span>

        </button>

      

        <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
          <ul class="navbar-nav mr-auto mt-2 mt-lg-0">

            <li class="nav-item active">

                    <a class="nav-link" href="{% url 'eventFinderApp:index' %}">Home</a>            </li>

            <li class="nav-item">

                    <a class="nav-link" href="{% url 'eventFinderApp:account' %}">My Account</a>            </li>

            <li class="nav-item">

                    {% if user.is_authenticated %}

                    <p>Hi {{ user.username }}</p>

                    <p><a class="nav-link" href="{% url 'logout' %}">logout</a></p>

                {% else %}

                    <p><a class="nav-link" href="{% url 'login' %}">login</a></p>

                {% endif %}            </li>

          </ul>

          <form class="form-inline my-2 my-lg-0">

            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">

            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>

          </form>

        </div>

      </nav> {% endcomment %}

eventFinderApp/templates/eventFinderApp/thanks.html
{% extends "base.html" %}
{% block content %}

{% load static %}

<!doctype html>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>EventFinda</title>
        <meta name="description" content="">
        <meta name="author" content="angela moroney">
        <link href="https://fonts.googleapis.com/css?family=Manjari&display=swap" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'eventFinderApp/style.css' %}">
    </head>

    <body>
      
            <div>
                <h1>Thank-you for adding to our events list, we really appreciate it!</h1>
            </div>
           
      

        {% comment %} {% block content %}{% endblock %} {% endcomment %}
    </body>
</html>

{% endblock %}