eventFinderApp/eventFinderProject/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from django.views.generic.base import TemplateView
from rest_framework import routers
from eventFinderApp import viewsets
from rest_framework.authtoken import views
from django.conf import settings
from django.conf.urls.static import static
from users import viewsets as UserViewsets

# from django.conf import settings
# from django.conf.urls.static import static

router = routers.DefaultRouter()
router.register(r'events', viewsets.EventViewSet)
router.register(r'users', UserViewsets.CustomUserViewSet)


urlpatterns = [
    path("", include("eventFinderApp.urls")),
    # path('', TemplateView.as_view(template_name='index.html'), name='index'),
    url(r"^admin/", admin.site.urls),
    path("users/", include("django.contrib.auth.urls")),
    path("users/", include("users.urls")),
    path("profile/edit/", include("users.urls")),
    path('api/', include(router.urls)),
    path(r'api-auth-token/', views.obtain_auth_token),
    
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eventFinderApp/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from . import views
from django.conf.urls import url

app_name = 'eventFinderApp'


urlpatterns = [

    # event-finder/

    path('', views.IndexView.as_view(), name='index'),

    # event-finder/1

    path('eventFinder/<int:pk>/', views.EventView.as_view(), name='event'),

    # event-finder/my-account

    path('my-account/', views.AccountView.as_view(), name='account'),

    # event-finder/add-event

    path('eventFinder/addevent/', views.addevent, name='addevent'),
    path('eventFinder/<id>/editevent/', views.editevent, name='editevent'),

    # path(r'^eventFinder/event/(?P<id>\d+)/$', views.editevent, name='editevent'),

    # path('eventFinder/(?P<id>\d+)/', views.editevent, name='edit'),

    # url(r'^eventFinderApp/addevent/$', views.addevent, name='addevent'),



    # event-finder/user

    # path("event/edit/", views.edit_event, name="edit_event"),
    # path('thanks/', views.thankyouView.as_view(), name='thanks'),

    # path('eventFinder/thanks/', TemplateView.as_view(template_name="thanks")),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eventFinderProject/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from django.views.generic.base import TemplateView
from rest_framework import routers
from eventFinderApp import viewsets
from rest_framework.authtoken import views
from django.conf import settings
from django.conf.urls.static import static
from users import viewsets as UserViewsets

# from django.conf import settings
# from django.conf.urls.static import static

router = routers.DefaultRouter()
router.register(r'events', viewsets.EventViewSet)
router.register(r'users', UserViewsets.CustomUserViewSet)


urlpatterns = [
    path("", include("eventFinderApp.urls")),
    # path('', TemplateView.as_view(template_name='index.html'), name='index'),
    url(r"^admin/", admin.site.urls),
    path("users/", include("django.contrib.auth.urls")),
    path("users/", include("users.urls")),
    path("profile/edit/", include("users.urls")),
    path('api/', include(router.urls)),
    path(r'api-auth-token/', views.obtain_auth_token),
    # url(r'^$/', include('eventFinderApp.urls')), #added this.
    
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, include
from django.conf.urls import include, url   
from . import views
from django.conf.urls.static import static
from django.views.generic import TemplateView

# from django.contrib.auth import views as auth_views




urlpatterns = [

    path("register/", views.Register.as_view(), name="register"),
    path("profile/edit/", views.edit_profile, name="edit_profile"),
    # url(r'^profile/edit/$', views.edit_profile, name = "edit_profile"),
    url(r'^profile/$', views.view_profile, name="view_profile"),
    # url(r'^change_password/$', views.change_password, name="change_password"),  
    # path('upload/', views.upload, name='upload'),
    path('pics/upload/', views.upload_pic, name="pic"),
    path("profile/password", views.change_password, name="edit password"),

]

templates/base.html
{% load static %}

<!doctype html>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>EventFinda</title>
        <meta name="description" content="">
        <meta name="author" content="Angela Moroney">
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link href="https://fonts.googleapis.com/css?family=Manjari&display=swap" rel="stylesheet">
      
    </head>

    <body>
        <header>
            <div>
                <h1>EventFinda</h1>
                <h2>Find free events near you!!!!!!</h2>
            </div>
            {% include './nav.html' %}
        </header>
        {% comment %} <a href="{% url 'addevent' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a> {% endcomment %}

        {% block content %}{% endblock %}
    </body>
</html>

templates/nav.html
{% load staticfiles %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons"> 
<link rel="stylesheet" type="text/css" href="{% static 'eventFinderApp/style.css' %}" />


<nav class="navbar navbar-expand-lg navbar-light bg-light">

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">

          <span class="navbar-toggler-icon"></span>

        </button>

      

        <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
        
          <ul class="navbar-nav mt-2 mt-lg-0">

            <li class="nav-item active">

                    <a class="nav-link" href="{% url 'eventFinderApp:index' %}">Home</a>            </li>

            <li class="nav-item">

                    <a class="nav-link" href="{% url 'eventFinderApp:account' %}">My Account</a>            </li>

            <li class="nav-item">

                    {% if user.is_authenticated %}

                    <a class="nav-link">Hi {{ user.first_name }}</a>

                    <a class="nav-link" href="{% url 'logout' %}">logout</a></li>

                {% else %}

                    <a class="nav-link" href="{% url 'login' %}">login</a></p>

                    <a class="nav-link" href="{% url 'register' %}">register</a></p>

                {% endif %}            </li>

          </ul>

          <form class="form-inline my-2 my-lg-0">

            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">

            <button type="submit" class="w3-bar-item w3-button w3-green"><i class="material-icons">search</i></button>

           
            {% comment %} <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button> {% endcomment %}

          </form>

        </div>

      </nav>



{% comment %} in case it goes wrong - here's what i had before: {% endcomment %}

{% comment %} 

      {% load staticfiles %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="{% static 'eventFinderApp/style.css' %}" />


<nav class="navbar navbar-expand-lg navbar-light bg-light">

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">

          <span class="navbar-toggler-icon"></span>

        </button>

      

        <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
          <ul class="navbar-nav mr-auto mt-2 mt-lg-0">

            <li class="nav-item active">

                    <a class="nav-link" href="{% url 'eventFinderApp:index' %}">Home</a>            </li>

            <li class="nav-item">

                    <a class="nav-link" href="{% url 'eventFinderApp:account' %}">My Account</a>            </li>

            <li class="nav-item">

                    {% if user.is_authenticated %}

                    <p>Hi {{ user.username }}</p>

                    <p><a class="nav-link" href="{% url 'logout' %}">logout</a></p>

                {% else %}

                    <p><a class="nav-link" href="{% url 'login' %}">login</a></p>

                {% endif %}            </li>

          </ul>

          <form class="form-inline my-2 my-lg-0">

            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">

            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>

          </form>

        </div>

      </nav> {% endcomment %}